modLoader="javafml"
loaderVersion="[43,)"
license="GNU GPL v3"
issueTrackerURL="https://github.com/Melara1024/Steves_Mini_Pouch_Mod/issues"

[[mods]]
modId="stevesminipouch"
version="${file.jarVersion}"
displayName="Steve's Mini Pouch"
displayURL="https://www.curseforge.com/minecraft/mc-mods/steves-mini-pouch"
displayTest="MATCH_VERSION"
logoFile="icon.png"
authors="Melara1024"
description='''This mod allows you to increase or decrease the number of slots and switch between inventory functions.More information will be posted on the Wiki on GitHub.'''

[[dependencies.stevesminipouch]]
   modId="forge"
   mandatory=true
   versionRange="[43,)"
   ordering="NONE"
   side="BOTH"

[[dependencies.stevesminipouch]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.19.2,1.20)"
   ordering="NONE"
   side="BOTH"
